#!/bin/sh

#LastCommitDate="$( git log -1 --format="%ai" )"
#LastCommitDate="$( git log -1 --format="%at" | xargs -I{} date -d @{} "+%Y-%m-%dT%H:%M:%SZ" )"


# LINK: https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
# option 1
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
# option 2
DIR="`dirname "$0"`"
#echo ${DIR}


python ${DIR}/takemeback.py --min 30 --max 55
